import { env } from 'process';
import { setGlobalDispatcher, ProxyAgent } from 'undici';

if (env.HTTPS_PROXY) {
  const dispatcher = new ProxyAgent({ uri: new URL(env.HTTPS_PROXY).toString() });
  setGlobalDispatcher(dispatcher);
}

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },

  modules: ['@nuxt/eslint', '@nuxt/image', '@nuxt/ui', '@nuxtjs/i18n', '@nuxtjs/mdc', '@vueuse/nuxt'],
  css: ['katex/dist/katex.min.css', '~/assets/css/main.css'],
  ssr: false,
  image: {
    provider: 'none',
  },
  mdc: {
    components: {
      prose: true,
    },
  },
  i18n: {
    strategy: 'no_prefix',
    defaultLocale: 'zh-CN',
    langDir: 'locales',
    locales: [
      { code: 'en', language: 'en', name: 'English', file: 'en.ts' },
      { code: 'zh-CN', language: 'zh-CN', name: '简体中文', file: 'zh-CN.ts' },
      { code: 'zh-TW', language: 'zh-TW', name: '繁體中文', file: 'zh-TW.ts' },
      { code: 'ja', language: 'ja', name: '日本語', file: 'ja.ts' },
    ],
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'rbph_locale',
      redirectOn: 'root',
    },
    vueI18n: './i18n.config.ts',
  },
  components: {
    global: true,
    dirs: [
      { path: './components/puzzle/rbph-puzzle-page', pathPrefix: true, prefix: 'rbph-puzzle-page' },
      { path: './components/account', pathPrefix: false },
      { path: './components/infrastructure', pathPrefix: false },
      { path: './components/shell', pathPrefix: false },
      { path: './components/ui', pathPrefix: false },
      { path: './components/content/renderers', pathPrefix: false },
      { path: './components/content/editor', pathPrefix: false },
      { path: './components/content/blocks', pathPrefix: false },
      { path: './components/puzzle', pathPrefix: false },
      { path: './components/round', pathPrefix: false },
      { path: './components/team', pathPrefix: false },
      { path: './components/ticket', pathPrefix: false },
      { path: './components/announcement', pathPrefix: false },
      { path: './components/admin/announcements', pathPrefix: false },
      { path: './components/admin/assets', pathPrefix: false },
      { path: './components/admin/puzzles', pathPrefix: false },
      { path: './components/admin/selectors', pathPrefix: false },
      { path: './components/admin/release', pathPrefix: false },
      { path: './components/admin/unlock', pathPrefix: false },
      { path: './components/admin/frontend', pathPrefix: false },
      { path: './components/theme/public', pathPrefix: false },
      { path: './components/theme/runtime', pathPrefix: false },
      { path: './components/theme/devtools', pathPrefix: false },
      { path: './components/prose', pathPrefix: false },
    ],
  },
  runtimeConfig: {
    public: {
      apiBase: process.env.NUXT_PUBLIC_API_BASE ?? '/api',
      themeDevServer: process.env.NUXT_PUBLIC_THEME_DEV_SERVER ?? '',
    },
  },
  vite: {
    server: {
      proxy: {
        '/api': {
          target: 'http://127.0.0.1:9999',
          changeOrigin: true,
          ws: true,
          secure: false,
        },
      },
    },
    optimizeDeps: {
      include: [
        '@codemirror/lang-html',
        '@codemirror/lang-javascript',
        '@codemirror/language',
        '@codemirror/state',
        '@codemirror/view',
        '@iconify/utils',
        '@iconify/vue',
        '@internationalized/date',
        '@lezer/highlight',
        '@tiptap/extension-color',
        '@tiptap/extension-table',
        '@tiptap/extension-table-cell',
        '@tiptap/extension-table-header',
        '@tiptap/extension-table-row',
        '@tiptap/extension-text-align',
        '@tiptap/extension-text-style',
        '@tiptap/extension-underline',
        '@zip.js/zip.js',
        'fflate',
        'hash-wasm',
        'katex',
        'tailwind-merge',
        'valibot',
      ],
    },
  },
  icon: {
    clientBundle: {
      scan: true,
      icons: [
        // nuxt ui defaults
        'lucide:arrow-down',
        'lucide:arrow-left',
        'lucide:arrow-right',
        'lucide:arrow-up',
        'lucide:circle-alert',
        'lucide:check',
        'lucide:chevrons-left',
        'lucide:chevrons-right',
        'lucide:chevron-down',
        'lucide:chevron-left',
        'lucide:chevron-right',
        'lucide:chevron-up',
        'lucide:x',
        'lucide:copy',
        'lucide:copy-check',
        'lucide:moon',
        'lucide:grip-vertical',
        'lucide:ellipsis',
        'lucide:circle-x',
        'lucide:arrow-up-right',
        'lucide:eye',
        'lucide:eye-off',
        'lucide:file',
        'lucide:folder',
        'lucide:folder-open',
        'lucide:hash',
        'lucide:info',
        'lucide:sun',
        'lucide:loader-circle',
        'lucide:menu',
        'lucide:minus',
        'lucide:panel-left-close',
        'lucide:panel-left-open',
        'lucide:plus',
        'lucide:rotate-ccw',
        'lucide:search',
        'lucide:square',
        'lucide:star',
        'lucide:circle-check',
        'lucide:monitor',
        'lucide:lightbulb',
        'lucide:upload',
        'lucide:triangle-alert',
      ],
    },
  },
});
