import type { Component } from 'vue';
import {
  LazyUAccordion as UAccordion,
  LazyUApp as UApp,
  LazyUAlert as UAlert,
  LazyUAvatar as UAvatar,
  LazyUAvatarGroup as UAvatarGroup,
  LazyUBadge as UBadge,
  LazyUBanner as UBanner,
  LazyUButton as UButton,
  LazyUCalendar as UCalendar,
  LazyUCard as UCard,
  LazyUCarousel as UCarousel,
  LazyUCheckbox as UCheckbox,
  LazyUCheckboxGroup as UCheckboxGroup,
  LazyUChip as UChip,
  LazyUCollapsible as UCollapsible,
  LazyUColorPicker as UColorPicker,
  LazyUContainer as UContainer,
  LazyUEmpty as UEmpty,
  LazyUFieldGroup as UFieldGroup,
  LazyUForm as UForm,
  LazyUFormField as UFormField,
  LazyUIcon as UIcon,
  LazyUInput as UInput,
  LazyUInputDate as UInputDate,
  LazyUInputMenu as UInputMenu,
  LazyUInputNumber as UInputNumber,
  LazyUInputTags as UInputTags,
  LazyUInputTime as UInputTime,
  LazyUKbd as UKbd,
  LazyUListbox as UListbox,
  LazyUMarquee as UMarquee,
  LazyUPageBody as UPageBody,
  LazyUPageCard as UPageCard,
  LazyUPageColumns as UPageColumns,
  LazyUPageFeature as UPageFeature,
  LazyUPageGrid as UPageGrid,
  LazyUPageHeader as UPageHeader,
  LazyUPageHero as UPageHero,
  LazyUPageList as UPageList,
  LazyUPageSection as UPageSection,
  LazyUPagination as UPagination,
  LazyUPinInput as UPinInput,
  LazyUProgress as UProgress,
  LazyURadioGroup as URadioGroup,
  LazyUScrollArea as UScrollArea,
  LazyUSelect as USelect,
  LazyUSelectMenu as USelectMenu,
  LazyUSeparator as USeparator,
  LazyUSkeleton as USkeleton,
  LazyUSlider as USlider,
  LazyUStepper as UStepper,
  LazyUSwitch as USwitch,
  LazyUTable as UTable,
  LazyUTabs as UTabs,
  LazyUTextarea as UTextarea,
  LazyUTimeline as UTimeline,
  LazyUTree as UTree,
  LazyUUser as UUser,
  LazyRbtAnnouncements as RbtAnnouncements,
  LazyRbtContent as RbtContent,
  LazyRbtContentBlocks as RbtContentBlocks,
  LazyRbtCurrencyBadges as RbtCurrencyBadges,
  LazyRbtLink as RbtLink,
  LazyRbtModal as RbtModal,
  LazyRbtPuzzleCard as RbtPuzzleCard,
  LazyRbtSubmitResult as RbtSubmitResult,
  LazyRbtSubmissions as RbtSubmissions,
  LazyRbtSubmitter as RbtSubmitter,
} from '#components';

export const RBT_COMPONENT_REGISTRY: Readonly<Record<string, Component>> = Object.freeze({
  UAccordion,
  UApp,
  UAlert,
  UAvatar,
  UAvatarGroup,
  UBadge,
  UBanner,
  UButton,
  UCalendar,
  UCard,
  UCarousel,
  UCheckbox,
  UCheckboxGroup,
  UChip,
  UCollapsible,
  UColorPicker,
  UContainer,
  UEmpty,
  UFieldGroup,
  UForm,
  UFormField,
  UIcon,
  UInput,
  UInputDate,
  UInputMenu,
  UInputNumber,
  UInputTags,
  UInputTime,
  UKbd,
  UListbox,
  UMarquee,
  UPageBody,
  UPageCard,
  UPageColumns,
  UPageFeature,
  UPageGrid,
  UPageHeader,
  UPageHero,
  UPageList,
  UPageSection,
  UPagination,
  UPinInput,
  UProgress,
  URadioGroup,
  UScrollArea,
  USelect,
  USelectMenu,
  USeparator,
  USkeleton,
  USlider,
  UStepper,
  USwitch,
  UTable,
  UTabs,
  UTextarea,
  UTimeline,
  UTree,
  UUser,
  RbtAnnouncements,
  RbtContent,
  RbtContentBlocks,
  RbtCurrencyBadges,
  RbtLink,
  RbtModal,
  RbtPuzzleCard,
  RbtSubmitResult,
  RbtSubmissions,
  RbtSubmitter,
});
